---
title: "How to generate tabs automatically "
output: html_document
---

```{r}
library(ggplot2)  
library(tidyverse)
library(mgcv)
library(nycflights13)
```

```{r}
model_list <- list()
model_list[[1]] <- mgcv::gam(data= flights %>% slice(1:1000), formula = arr_delay ~ s(air_time) + carrier, method = "REML"   )
model_list[[2]] <- mgcv::gam(data= flights %>% slice(1001:2000), formula = arr_delay ~ s(air_time) + carrier, method = "REML"   )
model_list[[3]] <- mgcv::gam(data= flights %>% slice(2001:3000), formula = arr_delay ~ s(air_time) + carrier, method = "REML"   )
```


ggplot2 and kable  must be enclosed in a print() statement.
mgcv::plot.gam() must not be in a print() statement.  

## ggplots and kables    {.tabset}  


```{r, results='asis' , echo = FALSE}
for(i in 1:3){
  cat(' \n \n')
  cat('### ggplot ',i,' \n')
    print( ggplot(flights,aes(x=carrier,y=arr_delay))+ geom_boxplot()+ ggtitle(paste("plot",i)))
  cat(' \n \n')
}

cat(' \n \n')

for(i in 1:3){
  cat('### kable ',i,' \n')
    aaa <- flights %>% group_by(carrier) %>% summarise(mean_arr_delay = mean(arr_delay))
    print(knitr::kable(aaa))
  cat(' \n \n')
}

cat(' \n \n')

```



## Plot.gams {.tabset}

```{r, results='asis' , echo = FALSE}


for (i in seq(1:3)){
  cat(' \n \n')
  cat('### Plot.gam ',i,' \n')
  cat("Parametric table \n \n")
  print(
    summary(model_list[[i]])$p.table %>%
      knitr::kable()
  )
  cat(' \n \n')
  
  
  cat("Spline table \n \n")
  print(
    summary(model_list[[i]])$s.table %>%
      knitr::kable()
  )
  cat(' \n \n')
  
  cat("Plots \n \n")
  mgcv::plot.gam(
    model_list[[i]],
    scale = 0,
    pages = 1,
    rug = FALSE,
    #select= 14,
    se = FALSE,
    shade= TRUE,
    trans = exp,
    #all.terms = TRUE#,
    shade.col = "lightgreen",
    seWithMean = TRUE,
    col = "#006EB3"
  )

  cat(' \n \n')  
} 

```
# conclusion   


that's it!
