---
title: "merge all elements of a list"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)  
library(tidyverse)
library(mgcv)
library(nycflights13)
library(scam)
library(gtools)
```

```{r}
model_list <- list()
model_list[[1]] <- glm(data= flights %>% slice(1:3000), formula = arr_delay ~ air_time + carrier)
model_list[[2]] <- mgcv::gam(data= flights %>% slice(1:3000), formula = arr_delay ~ s(air_time) + carrier, method = "REML"   )
model_list[[3]] <- scam::scam(data= flights %>% slice(1:3000), formula = arr_delay ~ s(air_time, bs= "mpi") + carrier)

models_to_evaluate <- seq(1:3)
```


# Model summaries
## Side-by-side parametric term  and spline term summaries

```{r}
#prepare model summary
model_parametric_summary_list <- list()
model_spline_summary_list <- list()

model_estimate_summary_list_for_side_by_side <- list()
model_spline_summary_list_for_side_by_side <- list()
for (i in models_to_evaluate){
  if(class(model_list[[i]])[[1]] %in% c("glm")){
    model_parametric_summary_list[[i]] <-  as.data.frame(summary(model_list[[i]])$coefficients) %>%
      mutate(signif = gtools::stars.pval(`Pr(>|t|)`)) %>%
      mutate(`Pr(>|t|)` = round(`Pr(>|t|)`,3),
             mode_variable = rownames(.)
      )%>%
      select(mode_variable, Estimate, `Std. Error`, `t value`, `Pr(>|t|)`, signif)%>%
      magrittr::set_rownames(c())
    
    
    z <- model_parametric_summary_list[[i]] %>%
      select(mode_variable, Estimate)
    z[paste0("Estimate", i )]= z$Estimate
    z <- z %>% select(-Estimate)
    model_estimate_summary_list_for_side_by_side[[i]] <- z
    
  } else if(class(model_list[[i]])[[1]] %in% c("gam")){
    model_parametric_summary_list[[i]] <-
      as.data.frame(mgcv::summary.gam(model_list[[i]])$p.table) %>%
      mutate(signif = gtools::stars.pval(`Pr(>|t|)`)) %>%
      mutate(`Pr(>|t|)` = round(`Pr(>|t|)`,3),
             mode_variable = rownames(.)
      ) %>%
      select(mode_variable, Estimate, `Std. Error`, `t value`, `Pr(>|t|)`, signif) %>%
      magrittr::set_rownames(c())
    
    z <- model_parametric_summary_list[[i]] %>%
      select(mode_variable, Estimate)
    z[paste0("Estimate", i )]= z$Estimate
    z <- z %>% select(-Estimate)
    model_estimate_summary_list_for_side_by_side[[i]] <- z
    
    
    model_spline_summary_list[[i]] <-
      as.data.frame(summary(model_list[[i]])$s.table) %>%
      mutate(signif = gtools::stars.pval(`p-value`)) %>%
      mutate(`p-value)` = round(`p-value`,3),
             mode_variable = rownames(.)
      ) %>%
      select(mode_variable, edf, `Ref.df`, F, `p-value`) %>%
      magrittr::set_rownames(c())
    
    z <- model_spline_summary_list[[i]] %>%
      select(mode_variable, edf)
    z[paste0("edf", i )]= z$edf
    z <- z %>% select(-edf)
    model_spline_summary_list_for_side_by_side[[i]] <- z
    
  } else if(class(model_list[[i]])[[1]] %in% c("scam")){
    model_parametric_summary_list[[i]] <-
      as.data.frame(scam::summary.scam(model_list[[i]])$p.table) %>%
      mutate(signif = gtools::stars.pval(`Pr(>|t|)`)) %>%
      mutate(`Pr(>|t|)` = round(`Pr(>|t|)`,3),
             mode_variable = rownames(.)
      ) %>%
      select(mode_variable, Estimate, `Std. Error`, `t value`, `Pr(>|t|)`, signif) %>%
      magrittr::set_rownames(c())
    
    z <- model_parametric_summary_list[[i]] %>%
      select(mode_variable, Estimate)
    z[paste0("Estimate", i )]= z$Estimate
    z <- z %>% select(-Estimate)
    model_estimate_summary_list_for_side_by_side[[i]] <- z
    
    model_spline_summary_list[[i]] <-
      as.data.frame(summary(model_list[[i]])$s.table) %>%
      mutate(signif = gtools::stars.pval(`p-value`)) %>%
      mutate(`p-value)` = round(`p-value`,3),
             mode_variable = rownames(.)
      ) %>%
      select(mode_variable, edf, `Ref.df`, F, `p-value`) %>%
      magrittr::set_rownames(c())
    
    z <- model_spline_summary_list[[i]] %>%
      select(mode_variable, edf)
    z[paste0("edf", i )]= z$edf
    z <- z %>% select(-edf)
    model_spline_summary_list_for_side_by_side[[i]] <- z
  }
}
```

```{r}
#Reduce comes from
# https://stackoverflow.com/questions/15078896/how-to-merge-all-elements-of-list-in-r

# filtering out of null elements using lengths() comes from
# mylist[lengths(mylist) != 0].
Reduce(full_join,model_estimate_summary_list_for_side_by_side[lengths(model_estimate_summary_list_for_side_by_side) != 0]) %>%
  knitr::kable()
```

```{r}
Reduce(full_join,model_spline_summary_list_for_side_by_side[lengths(model_spline_summary_list_for_side_by_side) != 0]) %>%
  knitr::kable()
```
## Detailed model summaries and spline plots {.tabset}

```{r, results='asis'}

for (i in models_to_evaluate){
  cat(' \n \n')
  cat('### Model ',i,' \n')
  cat("Parametric table \n \n")
  print(
    model_parametric_summary_list[[i]] %>%
      knitr::kable()
  )
  cat(' \n \n')
  
  if(class(model_list[[i]])[[1]] %in% c("gam", "scam")){
    cat("Spline table \n \n")
    print(
      model_spline_summary_list[[i]] %>%
        knitr::kable()
    )
    cat(' \n \n')
  }
  
  if(class(model_list[[i]])[[1]] %in% c("gam", "scam")){
    cat("Plots \n \n")
    if(class(model_list[[i]])[[1]] == "gam"){
      mgcv::plot.gam(
        model_list[[i]],
        scale = 0,
        pages = 1,
        rug = FALSE,
        #select= 14,
        se = FALSE,
        shade= TRUE,
        trans = exp,
        #all.terms = TRUE#,
        shade.col = "lightgreen",
        seWithMean = TRUE,
        col = "#006EB3"
      )
      
    } else if(class(model_list[[i]])[[1]] == "scam"){
      scam::plot.scam(model_list[[i]],
                      # select = 1,
                      scale = 0,
                      pages = 1,
                      rug = FALSE,
                      se = FALSE,
                      shade= TRUE,
                      trans = exp,
                      #all.terms = TRUE#,
                      #shade.col = "lightgreen",
                      #seWithMean = TRUE,
                      col = "#006EB3"
      )
      
      
      cat(' \n \n')
    }
  }
  
}
```
